name: firebase_admob_platform_view
description: firebase_admob for platform view
version: 0.0.2
author:
homepage:

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: ibe.hokuto.firebaseadmobplatformview
    pluginClass: FirebaseAdmobPlatformViewPlugin
